### ISSUE TITLE
Failed to load the task-list package

### ISSUE THREAD

**Issue by fbbdev** [kenwheeler/task-list#12]
Steps to reproduce:
1. Install atom v.0.190.0
2. Install task-list package
3. Run atom in 1.0 API preview mode: `atom -1`

**Atom Version**: 0.190.0
**System**: linux 3.19.3-200.fc21.x86_64
**Thrown From**: [task-list](https://github.com/kenwheeler/task-list) package, v0.7.0
### Stack Trace

Failed to load the task-list package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
  at __extends (/home/fabio/.atom/packages/task-list/lib/task-list-view.coffee:4:199)
  at /home/fabio/.atom/packages/task-list/lib/task-list-view.coffee:6:3
  at Object.<anonymous> (/home/fabio/.atom/packages/task-list/lib/task-list-view.coffee:124:5)
  at Object.<anonymous> (/home/fabio/.atom/packages/task-list/lib/task-list-view.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/usr/share/atom/resources/app/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/home/fabio/.atom/packages/task-list/lib/task-list.coffee:1:16)
  at Object.<anonymous> (/home/fabio/.atom/packages/task-list/lib/task-list.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/usr/share/atom/resources/app/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Package.module.exports.Package.requireMainModule (/usr/share/atom/resources/app/src/package.js:665:34)
  at /usr/share/atom/resources/app/src/package.js:174:28
  at Package.module.exports.Package.measure (/usr/share/atom/resources/app/src/package.js:152:15)
  at Package.module.exports.Package.load (/usr/share/atom/resources/app/src/package.js:166:12)
  at PackageManager.module.exports.PackageManager.loadPackage (/usr/share/atom/resources/app/src/package-manager.js:355:14)
  at PackageManager.module.exports.PackageManager.loadPackages (/usr/share/atom/resources/app/src/package-manager.js:325:14)
  at Atom.module.exports.Atom.startEditorWindow (/usr/share/atom/resources/app/src/atom.js:631:21)
  at Object.<anonymous> (/usr/share/atom/resources/app/src/window-bootstrap.js:12:8)
  at Object.<anonymous> (/usr/share/atom/resources/app/src/window-bootstrap.js:23:4)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (/usr/share/atom/resources/app/src/babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at window.onload (file:///usr/share/atom/resources/app/static/index.js:54:25)

```
### Commands

```
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
autocomplete-bibtex, v0.5.6
autocomplete-css, v0.6.0
autocomplete-glsl, v0.2.0
autocomplete-haskell, v0.2.1
autocomplete-html, v0.5.0
autocomplete-paths, v1.0.2
autocomplete-plus, v2.9.0
autocomplete-plus-jedi, v0.0.9
bezier-curve-editor, v0.6.6
color-picker, v1.6.0
fancy-new-file, v0.7.0
format-sql, v0.2.0
git-blame, v0.4.0
git-history, v2.5.0
git-log, v0.3.0
highlight-line, v0.10.1
linter, v0.12.0
linter-clang, v2.25.1
linter-javac, v0.1.3
linter-js-yaml, v1.0.0
linter-python-pep8, v0.2.0
minimap, v4.7.6
minimap-git-diff, v4.1.2
ogg-preview, v0.2.0
pdf-view, v0.17.0
project-manager, v1.15.5
quick-move-file, v0.7.0
scroll-sync, v0.1.1
svg-preview, v0.5.1
task-list, v0.7.0

# Dev
No dev packages
```

**Comment by fbbdev** [comment]
Probably a duplicate of #11

**Comment by PointedEars** [comment]
Steps to reproduce:
1. Try to load the package.

**Atom Version**: 1.9.0 (same problem with 1.8.0 and previous versions)
**System**: Mac OS X 10.11.6
**Thrown From**: [task-list](https://github.com/kenwheeler/task-list) package, v0.7.0

### Stack Trace

Failed to load the task-list package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (/Users/tholah/.atom/packages/task-list/lib/task-list-view.coffee:1:1)
    at /Users/tholah/.atom/packages/task-list/lib/task-list-view.coffee:6:3
    at Object.<anonymous> (/Users/tholah/.atom/packages/task-list/lib/task-list-view.coffee:6:3)
    at Object.<anonymous> (/Users/tholah/.atom/packages/task-list/lib/task-list-view.coffee:1:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/tholah/.atom/packages/task-list/lib/task-list.coffee:1:16)
    at Object.<anonymous> (/Users/tholah/.atom/packages/task-list/lib/task-list.coffee:1:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:715:27)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:117:28
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at Package.module.exports.Package.load (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:457:14)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:402:19
    at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:312:16)
    at PackageManager.module.exports.PackageManager.loadPackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:397:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:749:28
```

### Commands

```
```

### Config

``` json
{
  "core": {
    "automaticallyUpdate": false,
    "customFileTypes": {
      "source.ini": [
        ".buckconfig"
      ],
      "source.json": [
        ".arcconfig",
        "BUCK.autodeps"
      ],
      "source.python": [
        "BUCK"
      ]
    },
    "disabledPackages": [
      "linter-shellcheck",
      "ctrl-last-tab",
      "atom-jshint",
      "save-session",
      "linter",
      "fixmyjs",
      "git-tabs",
      "source-preview-jade",
      "keyboard-localization",
      "nav-panel",
      "source-preview-pug",
      "move-panes",
      "tab-smart-sort"
    ],
    "excludeVcsIgnoredPaths": false,
    "packagesWithKeymapsDisabled": [
      "open-on-github",
      "git-diff"
    ]
  }
}
```

### Installed Packages

``` coffee
# User
atom-beautify, v0.29.10 (inactive)
atom-css-comb, v3.1.0 (inactive)
atom-css-unit-converter, v1.1.1 (inactive)
atom-jshint, v2.0.0 (inactive)
atom-qunit-snippets, v1.1.0 (inactive)
atom-shell-commands, v1.4.0 (inactive)
atom-sort-projects, v1.6.0 (inactive)
atom-ternjs, v0.14.2 (inactive)
atom-x, v0.4.0 (inactive)
atomatigit, v1.5.5 (inactive)
auto-detect-indentation, v1.1.0 (inactive)
autoclose-html, v0.23.0 (inactive)
autocomplete-html-entities, v0.1.0 (inactive)
autocomplete-paths, v1.0.2 (inactive)
autoupdate-packages, v1.3.1 (inactive)
break-time, v0.3.0 (inactive)
browser-plus, vundefined (inactive)
character-table, v0.4.3 (inactive)
clipboard-plus, v0.5.1 (inactive)
color-picker, v2.2.2 (inactive)
column-select, v0.2.0 (inactive)
compare-files, v0.6.2 (inactive)
css-snippets, v0.9.0 (inactive)
css-specificity, v0.2.2 (inactive)
ctrl-last-tab, v0.3.0 (inactive)
docblockr, v0.7.4 (inactive)
docs-snippets, v0.8.0 (inactive)
es6-javascript, v1.0.0 (inactive)
ex-mode, v0.10.0 (inactive)
ex-mode-sort, v1.0.0 (inactive)
file-icons, vundefined (inactive)
filesize, v0.4.2 (inactive)
fixmyjs, v1.3.4 (inactive)
fold-comments, v0.6.0 (inactive)
git-blame, v0.4.8 (inactive)
git-clone, v0.1.5 (inactive)
git-control, v0.8.2 (inactive)
git-difftool, v0.2.7 (inactive)
git-go, v1.0.5 (inactive)
git-hide, v0.1.2 (inactive)
git-history, v3.2.0 (inactive)
git-log, v0.4.1 (inactive)
git-plus, v5.16.2 (inactive)
git-projects, v1.17.0 (inactive)
git-status, v0.3.4 (inactive)
git-tabs, v0.3.0 (inactive)
git-time-machine, v1.5.3 (inactive)
gitignore-snippets, v0.2.5 (inactive)
highlight-selected, v0.11.2 (inactive)
html2jade-plus, v1.0.0 (inactive)
jade-beautify, v0.1.5 (inactive)
jade-snippets, v0.5.0 (inactive)
javascript-snippets, v1.2.1 (inactive)
js-refactor, v0.7.3 (inactive)
keyboard-localization, v1.4.18 (inactive)
keyboard-scroll, v0.4.0 (inactive)
language-diff, v0.4.0 (inactive)
language-jade, v0.7.1 (inactive)
line-count-status, v0.0.3 (inactive)
lines, v0.13.1 (inactive)
linter, v1.11.14 (inactive)
linter-csslint, v1.3.2 (inactive)
linter-htmlhint, v1.3.0 (inactive)
linter-jade, v0.3.2 (inactive)
linter-jshint, v2.1.0 (inactive)
linter-less, v2.6.0 (inactive)
linter-shellcheck, v1.2.0 (inactive)
local-history, v3.3.0 (inactive)
markdown-scroll-sync, vundefined (inactive)
merge-conflicts, v1.4.4 (inactive)
minimap, v4.24.7 (inactive)
minimap-cursorline, v0.2.0 (inactive)
minimap-find-and-replace, v4.5.1 (inactive)
minimap-git-diff, v4.3.1 (inactive)
minimap-hide, v0.3.0 (inactive)
minimap-linter, v1.1.1 (inactive)
minimap-pigments, v0.2.1 (inactive)
minimap-split-diff, v0.3.1 (inactive)
multi-cursor-plus, v1.0.3 (inactive)
nav-panel, v0.0.11 (inactive)
navigate, v0.1.16 (inactive)
next-occurrence, v0.5.0 (inactive)
nodejs-snippets, v2.0.1 (inactive)
nuclide, v0.158.0 (inactive)
open-git-modified-files, v0.2.3 (inactive)
open-recent, v5.0.0 (inactive)
open-this, v0.2.0 (inactive)
pane-split-moves-tab, v0.1.0 (inactive)
pigments, v0.31.2 (inactive)
postcss-sorting, v2.7.0 (inactive)
preview-plus, v1.2.7 (inactive)
project-folder, v0.2.0 (inactive)
project-view, v0.5.0 (inactive)
recent-projects, v0.12.1 (inactive)
refactor, v0.9.2 (inactive)
regex-tester, v0.2.0 (inactive)
remember-file-positions, v0.2.2 (inactive)
restore-windows, v0.4.1 (inactive)
revert-buffer, v0.5.0 (inactive)
save-session, v0.16.0 (inactive)
script, v3.8.3 (inactive)
seti-ui, v1.3.1 (inactive)
show-origin, v0.2.0 (inactive)
smart-tab-name, v1.0.5 (inactive)
snippets-jade, v0.2.1 (inactive)
sort-lines, v0.14.0 (inactive)
source-preview-jade, v0.1.1 (inactive)
source-preview-pug, v0.2.0 (inactive)
split-diff, v1.0.3 (inactive)
stash-tabs, v0.1.0 (inactive)
Sublime-Style-Column-Selection, v1.6.0 (inactive)
symbols-tree-view, v0.13.2 (inactive)
tab-smart-sort, v0.1.4 (inactive)
task-list, v0.7.0 (inactive)
text-manipulation, v0.6.0 (inactive)
todo-show, v1.7.0 (inactive)
tree-view-git-branch, v0.1.2 (inactive)
tree-view-git-status, v1.0.2 (inactive)
up2date, v0.1.2 (inactive)
vim-mode-clipboard-plus, v0.2.0 (inactive)
vim-mode-plus, v0.49.1 (inactive)
xkcd-comics, v0.3.0 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.51.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.43.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.3.2 (inactive)
one-light-ui, v1.3.2 (inactive)
one-dark-syntax, v1.2.0 (inactive)
one-light-syntax, v1.2.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.2 (inactive)
archive-view, v0.61.1 (inactive)
autocomplete-atom-api, v0.10.0 (inactive)
autocomplete-css, v0.11.1 (inactive)
autocomplete-html, v0.7.2 (inactive)
autocomplete-plus, v2.31.0 (inactive)
autocomplete-snippets, v1.11.0 (inactive)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (inactive)
background-tips, v0.26.0 (inactive)
bookmarks, v0.41.0 (inactive)
bracket-matcher, v0.82.1 (inactive)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (inactive)
dev-live-reload, v0.47.0 (inactive)
encoding-selector, v0.22.0 (inactive)
exception-reporting, v0.38.1 (inactive)
fuzzy-finder, v1.3.0 (inactive)
git-diff, v1.1.0 (inactive)
find-and-replace, v0.198.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (inactive)
image-view, v0.58.0 (inactive)
incompatible-packages, v0.26.1 (inactive)
keybinding-resolver, v0.35.0 (inactive)
line-ending-selector, v0.5.0 (inactive)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (inactive)
metrics, v0.53.1 (inactive)
notifications, v0.64.1 (inactive)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.238.0 (inactive)
snippets, v1.0.2 (inactive)
spell-check, v0.67.1 (inactive)
status-bar, v1.4.0 (inactive)
styleguide, v0.46.0 (inactive)
symbols-view, v0.113.0 (inactive)
tabs, v0.98.0 (inactive)
timecop, v0.33.1 (inactive)
tree-view, v0.208.0 (inactive)
update-package-dependencies, v0.10.0 (inactive)
welcome, v0.34.0 (inactive)
whitespace, v0.32.2 (inactive)
wrap-guide, v0.38.1 (inactive)
language-c, v0.52.1 (inactive)
language-clojure, v0.21.0 (inactive)
language-coffee-script, v0.47.0 (inactive)
language-csharp, v0.12.1 (inactive)
language-css, v0.36.2 (inactive)
language-gfm, v0.86.0 (inactive)
language-git, v0.13.0 (inactive)
language-go, v0.42.0 (inactive)
language-html, v0.44.1 (inactive)
language-hyperlink, v0.16.0 (inactive)
language-java, v0.22.0 (inactive)
language-javascript, v0.119.0 (inactive)
language-json, v0.18.0 (inactive)
language-less, v0.29.3 (inactive)
language-make, v0.22.2 (inactive)
language-mustache, v0.13.0 (inactive)
language-objective-c, v0.15.1 (inactive)
language-perl, v0.35.0 (inactive)
language-php, v0.37.0 (inactive)
language-property-list, v0.8.0 (inactive)
language-python, v0.45.0 (inactive)
language-ruby, v0.68.5 (inactive)
language-ruby-on-rails, v0.25.0 (inactive)
language-sass, v0.52.0 (inactive)
language-shellscript, v0.22.3 (inactive)
language-source, v0.9.0 (inactive)
language-sql, v0.21.1 (inactive)
language-text, v0.7.1 (inactive)
language-todo, v0.28.0 (inactive)
language-toml, v0.18.0 (inactive)
language-xml, v0.34.8 (inactive)
language-yaml, v0.26.0 (inactive)

# Dev
No dev packages
```

**Comment by Cybermandrake** [comment]
One more, this time on Atom 1.10. After the scary message, the package shows up on package list, but doesn't seem to work.
1. Open Atom
2. Search "task" packages to install
3. Choose `task-list`
4. Wait

**Atom Version**: 1.10.2
**Electron Version**: 0.37.8
**System**: Ubuntu 16.04.1
**Thrown From**: [task-list](https://github.com/kenwheeler/task-list) package, v0.7.0

### Stack Trace

Failed to load the task-list package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (/home/william/.atom/packages/task-list/lib/task-list-view.coffee:1:1)
    at /home/william/.atom/packages/task-list/lib/task-list-view.coffee:6:3
    at Object.<anonymous> (/home/william/.atom/packages/task-list/lib/task-list-view.coffee:6:3)
    at Object.<anonymous> (/home/william/.atom/packages/task-list/lib/task-list-view.coffee:1:1)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/william/.atom/packages/task-list/lib/task-list.coffee:1:16)
    at Object.<anonymous> (/home/william/.atom/packages/task-list/lib/task-list.coffee:1:1)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/usr/share/atom/resources/app.asar/src/package.js:718:27)
    at /usr/share/atom/resources/app.asar/src/package.js:117:28
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:92:15)
    at Package.module.exports.Package.load (/usr/share/atom/resources/app.asar/src/package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/usr/share/atom/resources/app.asar/src/package-manager.js:457:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:536:30)
    at /usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:460:29
    at exit (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:73:16)
    at triggerExitCallback (/usr/share/atom/resources/app.asar/src/buffered-process.js:215:47)
    at /usr/share/atom/resources/app.asar/src/buffered-process.js:229:18
    at Socket.<anonymous> (/usr/share/atom/resources/app.asar/src/buffered-process.js:100:18)
    at emitOne (events.js:95:20)
    at Socket.emit (events.js:182:7)
    at Pipe._onclose (net.js:477:12)
```

### Commands

```
     -9:50.4.0 markdown-writer:insert-new-line (atom-text-editor.editor.is-focused)
     -9:50.4.0 editor:newline (atom-text-editor.editor.is-focused)
  4x -9:23.7.0 core:backspace (atom-text-editor.editor.mini.is-focused)
 25x -9:20.2.0 core:page-down (atom-text-editor.editor.mini.is-focused)
     -5:17.2.0 core:page-up (atom-text-editor.editor.mini.is-focused)
     -5:16.7.0 core:page-down (atom-text-editor.editor.mini.is-focused)
  2x -5:15.5.0 core:page-up (atom-text-editor.editor.mini.is-focused)
  2x -0:08.6.0 core:page-down (atom-text-editor.editor.mini.is-focused)
```

### Config

``` json
{
  "core": {
    "disabledPackages": [
      "language-gfm"
    ]
  }
}
```

### Installed Packages

``` coffee
# User
git-time-machine, v1.5.3 (inactive)
language-markdown, v0.16.3 (active)
language-textile, v0.2.0 (active)
markdown-preview-plus, v2.4.0 (active)
markdown-scroll-sync, v2.1.2 (active)
markdown-toc, v0.4.1 (inactive)
markdown-writer, v2.6.0 (active)
pandoc-convert, v1.1.0 (active)
task-list, v0.7.0 (inactive)
text-manipulation, v0.6.0 (active)
textile-preview, v0.1.1 (active)
url-encode, v0.5.0 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.5.0 (active)
one-light-ui, v1.5.0 (inactive)
one-dark-syntax, v1.3.0 (active)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.3 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (active)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
find-and-replace, v0.201.0 (inactive)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.2 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.65.0 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.100.2 (active)
timecop, v0.33.2 (active)
tree-view, v0.208.2 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (inactive)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by Nearoo** [comment]
This is the issue people get lead to by atom when the error is thrown, so you might want to consider to actually close #11 instead of this one.
