### ISSUE TITLE
Uncaught TypeError: Cannot read property 'prototype' of undefined

### ISSUE THREAD

**Issue by roymap** [kenwheeler/task-list#17]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.0
**System**: Mac OS X 10.10.3
**Thrown From**: [task-list](https://github.com/kenwheeler/task-list) package, v0.7.0
### Stack Trace

Uncaught TypeError: Cannot read property 'prototype' of undefined

```
At /Users/rperiera/.atom/packages/task-list/lib/task-list-view.coffee:4

TypeError: Cannot read property 'prototype' of undefined
  at __extends (/Users/rperiera/.atom/packages/task-list/lib/task-list-view.coffee:4:199)
  at /Users/rperiera/.atom/packages/task-list/lib/task-list-view.coffee:6:3
  at Object.<anonymous> (/Users/rperiera/.atom/packages/task-list/lib/task-list-view.coffee:124:5)
  at Object.<anonymous> (/Users/rperiera/.atom/packages/task-list/lib/task-list-view.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/rperiera/.atom/packages/task-list/lib/task-list.coffee:1:16)
  at Object.<anonymous> (/Users/rperiera/.atom/packages/task-list/lib/task-list.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:709:34)
  at Package.module.exports.Package.activateConfig (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:257:12)
  at PackageDetailView.module.exports.PackageDetailView.activate (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:163:26)
  at PackageDetailView.module.exports.PackageDetailView.updateInstalledState (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:201:12)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:235:24
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/emissary/lib/emitter.js:155:30
  at Array.forEach (native)
  at PackageManager.module.exports.Emitter.emitSlow (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/emissary/lib/emitter.js:154:47)
  at PackageManager.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/emissary/lib/emitter.js:107:30)
  at PackageManager.module.exports.PackageManager.emitPackageEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:546:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:369:26
  at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:53:16)
  at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:220:18
  at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:98:18)
  at emitOne (events.js:82:20)
  at Socket.emit (events.js:166:7)
  at Pipe.close (net.js:464:12)

```
### Commands

```
     -8:16.7.0 settings-view:install-packages-and-themes (atom-text-editor.editor)
     -8:13.7.0 editor:select-to-first-character-of-line (atom-text-editor.editor.mini.is-focused)
     -8:12 core:confirm (atom-text-editor.editor.mini.is-focused)
     -7:53.5.0 editor:select-to-first-character-of-line (atom-text-editor.editor.mini.is-focused)
     -7:50.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -7:13.5.0 project-find:show (atom-text-editor.editor.is-focused)
     -7:01.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -4:26 command-palette:toggle (atom-text-editor.editor.is-focused)
  8x -4:21.5.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -4:19.3.0 core:move-up (atom-text-editor.editor.mini.is-focused)
     -4:17.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -4:17.8.0 settings-view:install-packages-and-themes (atom-text-editor.editor)
 13x -4:14.3.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -4:11.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:39.4.0 editor:select-to-first-character-of-line (atom-text-editor.editor.mini.is-focused)
     -1:36.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "monokai"
    ],
    "disabledPackages": [
      "npm-docs",
      "npm-docs"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
angularjs, v0.3.0
autocomplete-php, v0.3.6
color-picker, v2.0.7
language-mongodb, v0.2.0
language-smarty-php, v0.5.0
linter-php, v0.0.15
monokai, v0.14.0

# Dev
No dev packages
```

**Comment by tomolt** [comment]
Same problem here on Arch Linux + Atom 1.0.0

**Comment by danrasmuson** [comment]
I'm getting this issue as well.

**Comment by mkxml** [comment]
Same problem OS X 10.11
