### ISSUE TITLE
Failed to activate the task-list package

### ISSUE THREAD

**Issue by CameronGarrett** [kenwheeler/task-list#18]
1. open file with a TODO in editor
2. press ctrl-alt-t

**Atom Version**: 1.0.0
**System**: Mac OS X 10.10.3
**Thrown From**: [task-list](https://github.com/kenwheeler/task-list) package, v0.7.0
### Stack Trace

Failed to activate the task-list package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
  at __extends (/Users/camerongarrett/.atom/packages/task-list/lib/task-list-view.coffee:1:1)
  at /Users/camerongarrett/.atom/packages/task-list/lib/task-list-view.coffee:6:3
  at Object.<anonymous> (/Users/camerongarrett/.atom/packages/task-list/lib/task-list-view.coffee:124:5)
  at Object.<anonymous> (/Users/camerongarrett/.atom/packages/task-list/lib/task-list-view.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/camerongarrett/.atom/packages/task-list/lib/task-list.coffee:1:16)
  at Object.<anonymous> (/Users/camerongarrett/.atom/packages/task-list/lib/task-list.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Package.module.exports.Package.requireMainModule (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/package.js:709:34)
  at Package.module.exports.Package.activateConfig (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/package.js:257:12)
  at Package.module.exports.Package.activateNow (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/package.js:236:14)
  at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/package.js:772:25
  at Emitter.module.exports.Emitter.emit (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/command-registry.js:222:20)
  at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:180:20)

```
### Commands

```
  3x -1:23.8.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:38.4.0 core:copy (atom-text-editor.editor.is-focused)
     -0:28.6.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -0:28.6.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:26.2.0 core:move-down (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:25.9.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:25.8.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:18.7.0 core:save (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:14.9.0 editor:toggle-line-comments (atom-text-editor.editor.is-focused)
  2x -0:14.7.0 core:save (atom-text-editor.editor.is-focused)
     -0:05.7.0 task-list:toggle (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "audioBeep": false
  }
}
```
### Installed Packages

``` coffee
# User
atom-beautify, v0.28.7
color-picker, v2.0.7
emmet, v2.3.10
gutter-shadow, v0.5.0
indent-guide-improved, v1.4.0
minimap, v4.10.0
minimap-autohide, v0.10.0
minimap-bookmarks, v0.1.0
minimap-find-and-replace, v4.2.0
minimap-git-diff, v4.1.3
minimap-highlight-selected, v4.3.0
minimap-selection, v4.2.0
pigments, v0.8.1
save-session, v0.15.5
task-list, v0.7.0
tidy-markdown, v1.0.0

# Dev
No dev packages
```

**Comment by KevinFerret-a1** [comment]
Same here.
1. Edit file by adding TODO items in the comments
2. Toggle TODO list (either via command palette or via keyboard shortcut)

**Atom Version**: 1.0.0
**System**: Mac OS X 10.10.3
**Thrown From**: [task-list](https://github.com/kenwheeler/task-list) package, v0.7.0

### Stack Trace

Failed to activate the task-list package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
  at __extends (/Users/kevinferret/.atom/packages/task-list/lib/task-list-view.coffee:1:1)
  at /Users/kevinferret/.atom/packages/task-list/lib/task-list-view.coffee:6:3
  at Object.<anonymous> (/Users/kevinferret/.atom/packages/task-list/lib/task-list-view.coffee:124:5)
  at Object.<anonymous> (/Users/kevinferret/.atom/packages/task-list/lib/task-list-view.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/kevinferret/.atom/packages/task-list/lib/task-list.coffee:1:16)
  at Object.<anonymous> (/Users/kevinferret/.atom/packages/task-list/lib/task-list.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:709:34)
  at Package.module.exports.Package.activateConfig (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:257:12)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:236:14)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:772:25
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:222:20)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:159:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
  at space-pen-div.atom.commands.add.core:confirm (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:180:20)

```

### Commands

```
     -1:02.6.0 core:select-all (atom-text-editor.editor.is-focused)
     -1:02.1.0 core:copy (atom-text-editor.editor.is-focused)
     -0:56.6.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:40.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:37.9.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:18 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:16.3.0 core:save (atom-text-editor.editor.is-focused)
     -0:13.8.0 command-palette:toggle (atom-text-editor.editor.is-focused)
  6x -0:10.5.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:03.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:03.0 task-list:toggle (atom-text-editor.editor)
```

### Config

``` json
{
  "core": {}
}
```

### Installed Packages

``` coffee
# User
atom-beautify, v0.28.7
linter, v1.1.0
linter-php, v0.0.15
minimap, v4.10.2
task-list, v0.7.0

# Dev
No dev packages
```

**Comment by mkxml** [comment]
+1, same thing here.

**Comment by DLMousey** [comment]
Still not fixed, another +1 here unfortunately :(

**Comment by llagerlof** [comment]
I am not sure if it's the same error, however:

**Failed to load the task-list package**

To reproduce:
1. Install the package.
2. Boom!

**Atom Version**: 1.7.4
**System**: Windows 8 64 bits
**Thrown From**: [task-list](https://github.com/kenwheeler/task-list) package, v0.7.0

### Stack Trace

Failed to load the task-list package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (file:///C:/Users/lawrence/.atom/packages/task-list/lib/task-list-view.coffee:1:1)
    at file:///C:/Users/lawrence/.atom/packages/task-list/lib/task-list-view.coffee:6:3
    at Object.<anonymous> (file:///C:/Users/lawrence/.atom/packages/task-list/lib/task-list-view.coffee:6:3)
    at Object.<anonymous> (file:///C:/Users/lawrence/.atom/packages/task-list/lib/task-list-view.coffee:1:1)
    at Module._compile (C:\Users\lawrence\AppData\Local\atom\app-1.7.4\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (C:\Users\lawrence\AppData\Local\atom\app-1.7.4\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (C:\Users\lawrence\AppData\Local\atom\app-1.7.4\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (file:///C:/Users/lawrence/.atom/packages/task-list/lib/task-list.coffee:1:16)
    at Object.<anonymous> (file:///C:/Users/lawrence/.atom/packages/task-list/lib/task-list.coffee:1:1)
    at Module._compile (C:\Users\lawrence\AppData\Local\atom\app-1.7.4\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (C:\Users\lawrence\AppData\Local\atom\app-1.7.4\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (C:\Users\lawrence\AppData\Local\atom\app-1.7.4\resources\app.asar\src\native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (C:\Users\lawrence\AppData\Local\atom\app-1.7.4\resources\app.asar\src\package.js:715:27)
    at C:\Users\lawrence\AppData\Local\atom\app-1.7.4\resources\app.asar\src\package.js:117:28
    at Package.module.exports.Package.measure (C:\Users\lawrence\AppData\Local\atom\app-1.7.4\resources\app.asar\src\package.js:92:15)
    at Package.module.exports.Package.load (C:\Users\lawrence\AppData\Local\atom\app-1.7.4\resources\app.asar\src\package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (C:\Users\lawrence\AppData\Local\atom\app-1.7.4\resources\app.asar\src\package-manager.js:457:14)
    at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\lawrence\AppData\Local\atom\app-1.7.4\resources\app.asar\src\package-manager.js:536:30)
    at C:\Users\lawrence\AppData\Local\atom\app-1.7.4\resources\app.asar\node_modules\settings-view\lib\package-manager.js:452:29
    at exit (C:\Users\lawrence\AppData\Local\atom\app-1.7.4\resources\app.asar\node_modules\settings-view\lib\package-manager.js:73:16)
    at triggerExitCallback (C:\Users\lawrence\AppData\Local\atom\app-1.7.4\resources\app.asar\src\buffered-process.js:215:47)
    at ChildProcess.<anonymous> (C:\Users\lawrence\AppData\Local\atom\app-1.7.4\resources\app.asar\src\buffered-process.js:237:18)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```

### Commands

```
     -9:28.6.0 core:save (atom-text-editor.editor.is-focused)
     -9:27.9.0 core:move-up (atom-text-editor.editor.is-focused)
     -9:27.5.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
  2x -9:26 editor:move-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -9:23.8.0 core:save (atom-text-editor.editor.is-focused)
     -9:22.7.0 editor:move-to-end-of-word (atom-text-editor.editor.is-focused)
  4x -9:22.1.0 core:move-left (atom-text-editor.editor.is-focused)
     -7:17.1.0 core:save (atom-text-editor.editor.is-focused)
  2x -7:14.8.0 core:move-left (atom-text-editor.editor.is-focused)
     -7:14.4.0 core:move-right (atom-text-editor.editor.is-focused)
  2x -7:13.9.0 editor:select-to-end-of-word (atom-text-editor.editor.is-focused)
  3x -7:13.3.0 core:select-right (atom-text-editor.editor.is-focused)
     -7:12.1.0 core:copy (atom-text-editor.editor.is-focused)
     -7:11.8.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
  2x -7:11.5.0 editor:move-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -1:51.4.0 core:paste (atom-text-editor.editor.mini.is-focused)
```

### Config

``` json
{
  "core": {
    "allowPendingPaneItems": false,
    "disabledPackages": [
      "quick-query",
      "language-smarty-php",
      "minimap",
      "remote-edit",
      "emmet",
      "activate-power-mode",
      "regex-tester",
      "php-class-tree",
      "php-integrator-base",
      "tree-view"
    ],
    "fileEncoding": "iso88591",
    "openEmptyEditorOnStart": false
  }
}
```

### Installed Packages

``` coffee
# User
advanced-open-file, v0.16.3
autocomplete-php, v0.3.7
copy-path, v0.4.0
custom-title, v1.0.1
docblockr, v0.7.3
file-icons, v1.7.13
file-watcher, v0.4.0
language-smarty, v1.7.0
line-ending-converter, v1.3.2
linter, v1.11.4
linter-php, v1.2.0
pinned-tabs, v0.2.3
Sublime-Style-Column-Selection, v1.5.1
tabs-to-spaces, v1.0.2
task-list, v0.7.0

# Dev
No dev packages
```
