### ISSUE TITLE
task list not installing - cannot read property of prototype

### ISSUE THREAD

**Issue by millerthegorilla** [kenwheeler/task-list#21]
[Enter steps to reproduce below:]
1. Attempt to install task-list
2. error report occurs - see below

**Atom Version**: 1.8.0
**System**: Ubuntu 16.04
**Thrown From**: [task-list](https://github.com/kenwheeler/task-list) package, v0.7.0
### Stack Trace

Failed to load the task-list package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (/home/super/.atom/packages/task-list/lib/task-list-view.coffee:1:1)
    at /home/super/.atom/packages/task-list/lib/task-list-view.coffee:6:3
    at Object.<anonymous> (/home/super/.atom/packages/task-list/lib/task-list-view.coffee:6:3)
    at Object.<anonymous> (/home/super/.atom/packages/task-list/lib/task-list-view.coffee:1:1)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/super/.atom/packages/task-list/lib/task-list.coffee:1:16)
    at Object.<anonymous> (/home/super/.atom/packages/task-list/lib/task-list.coffee:1:1)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/usr/share/atom/resources/app.asar/src/package.js:715:27)
    at /usr/share/atom/resources/app.asar/src/package.js:117:28
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:92:15)
    at Package.module.exports.Package.load (/usr/share/atom/resources/app.asar/src/package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/usr/share/atom/resources/app.asar/src/package-manager.js:457:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:536:30)
    at /usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:452:29
    at exit (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:73:16)
    at triggerExitCallback (/usr/share/atom/resources/app.asar/src/buffered-process.js:215:47)
    at /usr/share/atom/resources/app.asar/src/buffered-process.js:229:18
    at Socket.<anonymous> (/usr/share/atom/resources/app.asar/src/buffered-process.js:100:18)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```
### Commands

```
     -4:48.8.0 timecop:view (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -4:35.2.0 activate-power-mode:toggle (div.timecop.pane-item.native-key-bindings)
     -4:17.9.0 gulp-manager:add (atom-text-editor.editor.power-mode.is-focused)
     -3:55.3.0 symbols-view:toggle-project-symbols (button.tab-button.selected)
     -3:07.4.0 command-palette:toggle (atom-text-editor.editor.power-mode.is-focused)
     -3:05.3.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  8x -3:01.1.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -2:58.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -2:58.5.0 settings-view:install-packages-and-themes (atom-text-editor.editor.power-mode)
  6x -1:24.7.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -1:11.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
 15x -0:58.8.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:27.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{}
```
### Installed Packages

``` coffee
# User
activate-power-mode, v0.7.0
atom-lorempixel, v0.1.0
atomic-chrome, v0.3.0
autocomplete-json, v5.1.0
autocomplete-ruby, v0.1.0
bottom-dock, v0.4.4
build-gulp, v0.11.0
gulp-manager, v0.2.19
gulp-snippets, v0.6.2
lint, v0.0.1
pigments, v0.31.1
symbols-tree-view, v0.13.2
task-list, v0.7.0

# Dev
No dev packages
```

**Comment by MoritzKn** [comment]
I have the same issue.
