### ISSUE TITLE
Failed to load the task-list package

### ISSUE THREAD

**Issue by jiaoyin** [kenwheeler/task-list#22]
Stack Trace
Failed to load the task-list package
Cannot read property 'prototype' of undefined
Hide Stack Trace
TypeError: Cannot read property 'prototype' of undefined
    at extend (file:///C:/Users/admin/.atom/packages/task-list/lib/task-list-view.coffee:1:1)
    at file:///C:/Users/admin/.atom/packages/task-list/lib/task-list-view.coffee:5:7
    at Object.<anonymous> (file:///C:/Users/admin/.atom/packages/task-list/lib/task-list-view.coffee:56:11)
    at Object.<anonymous> (file:///C:/Users/admin/.atom/packages/task-list/lib/task-list-view.coffee:1:1)
    at Module._compile (C:\Users\admin\AppData\Local\atom\app-1.15.0\resources\app.asar\src\native-compile-cache.js:109:30)
    at Object.value [as .coffee] (C:\Users\admin\AppData\Local\atom\app-1.15.0\resources\app.asar\src\compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (C:\Users\admin\AppData\Local\atom\app-1.15.0\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (file:///C:/Users/admin/.atom/packages/task-list/lib/task-list.coffee:1:16)
    at Object.<anonymous> (file:///C:/Users/admin/.atom/packages/task-list/lib/task-list.coffee:1:1)
    at Module._compile (C:\Users\admin\AppData\Local\atom\app-1.15.0\resources\app.asar\src\native-compile-cache.js:109:30)
    at Object.value [as .coffee] (C:\Users\admin\AppData\Local\atom\app-1.15.0\resources\app.asar\src\compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (C:\Users\admin\AppData\Local\atom\app-1.15.0\resources\app.asar\src\native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (C:\Users\admin\AppData\Local\atom\app-1.15.0\resources\app.asar\src\package.js:796:27)
    at C:\Users\admin\AppData\Local\atom\app-1.15.0\resources\app.asar\src\package.js:123:28
    at Package.module.exports.Package.measure (C:\Users\admin\AppData\Local\atom\app-1.15.0\resources\app.asar\src\package.js:96:15)
    at Package.module.exports.Package.load (C:\Users\admin\AppData\Local\atom\app-1.15.0\resources\app.asar\src\package.js:110:12)
    at PackageManager.module.exports.PackageManager.loadPackage (C:\Users\admin\AppData\Local\atom\app-1.15.0\resources\app.asar\src\package-manager.js:468:14)
    at C:\Users\admin\AppData\Local\atom\app-1.15.0\resources\app.asar\src\package-manager.js:412:19
    at Config.module.exports.Config.transact (C:\Users\admin\AppData\Local\atom\app-1.15.0\resources\app.asar\src\config.js:312:16)
    at PackageManager.module.exports.PackageManager.loadPackages (C:\Users\admin\AppData\Local\atom\app-1.15.0\resources\app.asar\src\package-manager.js:407:19)
    at C:\Users\admin\AppData\Local\atom\app-1.15.0\resources\app.asar\src\atom-environment.js:792:28

**Comment by kurtlove** [comment]
Same issue on the Mac (16GB RAM, MAC OS Sierra V. 10.12.3 (16D32))



TypeError: Cannot read property 'prototype' of undefined
    at extend (/Users/phiber/.atom/packages/task-list/lib/task-list-view.coffee:1:1)
    at /Users/phiber/.atom/packages/task-list/lib/task-list-view.coffee:5:7
    at Object.<anonymous> (/Users/phiber/.atom/packages/task-list/lib/task-list-view.coffee:56:11)
    at Object.<anonymous> (/Users/phiber/.atom/packages/task-list/lib/task-list-view.coffee:1:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:109:30)
    at Object.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/phiber/.atom/packages/task-list/lib/task-list.coffee:1:16)
    at Object.<anonymous> (/Users/phiber/.atom/packages/task-list/lib/task-list.coffee:1:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:109:30)
    at Object.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:796:27)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:123:28
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:96:15)
    at Package.module.exports.Package.load (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:110:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:468:14)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:412:19
    at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:312:16)
    at PackageManager.module.exports.PackageManager.loadPackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:407:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:792:28

**Comment by kurtlove** [comment]
TypeError: Cannot read property 'prototype' of undefined
    at extend (/Users/phiber/.atom/packages/task-list/lib/task-list-view.coffee:1:1)
    at /Users/phiber/.atom/packages/task-list/lib/task-list-view.coffee:5:7
    at Object.<anonymous> (/Users/phiber/.atom/packages/task-list/lib/task-list-view.coffee:56:11)
    at Object.<anonymous> (/Users/phiber/.atom/packages/task-list/lib/task-list-view.coffee:1:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:109:30)
    at Object.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/phiber/.atom/packages/task-list/lib/task-list.coffee:1:16)
    at Object.<anonymous> (/Users/phiber/.atom/packages/task-list/lib/task-list.coffee:1:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:109:30)
    at Object.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:796:27)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:123:28
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:96:15)
    at Package.module.exports.Package.load (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:110:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:468:14)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:412:19
    at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:312:16)
    at PackageManager.module.exports.PackageManager.loadPackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:407:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:792:28

**Comment by yi-ge** [comment]
Failed to load the task-list package
Cannot read property 'prototype' of undefined
Hide Stack Trace
TypeError: Cannot read property 'prototype' of undefined
    at extend (/Users/yige/.atom/packages/task-list/lib/task-list-view.coffee:1:1)
    at /Users/yige/.atom/packages/task-list/lib/task-list-view.coffee:5:7
    at Object.<anonymous> (/Users/yige/.atom/packages/task-list/lib/task-list-view.coffee:56:11)
    at Object.<anonymous> (/Users/yige/.atom/packages/task-list/lib/task-list-view.coffee:1:1)
    at Object.<anonymous> (/Users/yige/.atom/packages/task-list/lib/task-list-view.coffee:1:1)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at Object.<anonymous> (/Users/yige/.atom/packages/task-list/lib/task-list.coffee:1:16)
    at Object.<anonymous> (/Users/yige/.atom/packages/task-list/lib/task-list.coffee:1:1)
    at Object.<anonymous> (/Users/yige/.atom/packages/task-list/lib/task-list.coffee:1:1)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:96:26)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app/src/package.js:903:35)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:158:34
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:99:21)
    at Package.module.exports.Package.load (/Applications/Atom.app/Contents/Resources/app/src/package.js:144:18)
    at PackageManager.loadAvailablePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:617:16)
    at config.transact (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:530:20)
    at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app/src/config.js:342:22)

**Comment by BenjaminHoegh** [comment]
I will try look into this and see if I can make a fixed version of the plugin

**Comment by Sod-Almighty** [comment]
I guess you....forgot about it?

If you're not going to fix it, then kindly remove it from the Atom repo to avoid wasting people's time.
